version: '3.3'

services:
  db:
    image: mysql:5.7 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: QV=5bVX2 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpressuser 
      MYSQL_PASSWORD: 7k0xAS*x 

  wordpress:
    depends_on:
      - db
    image: wordpress:latest 
    network: host
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpressuser 
      WORDPRESS_DB_PASSWORD: 7k0xAS*x 
      WORDPRESS_DB_NAME: wordpress 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: QV=5bVX2 

volumes:
    db_data: {}