version: '3.3'

services:
  db:
    image: mysql:8.0 
    volumes:
      - db_data:/var/lib/mysql
    restart: always
   
    environment:
      MYSQL_ROOT_PASSWORD: QV=5bVX2 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpressuser 
      MYSQL_PASSWORD: 7k0xAS*x 

  wordpress:
    depends_on:
      - db
    image: your_build_name:latest 
    ports:
      - 80:80
    restart: always

               
volumes:
    db_data: {}

